id: I06A8DCC4
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:28:58.933589'
last_modified: '2022-05-31T05:28:58.933594'
parser: null
source_metadata:
  title: Namkha Tsewang Chokdrup Series
  language: bo
  description: 'Texts by and about Namkha Tsewang Chokdrup (nam mkha’ tshe dbang mchog
    grub, b. 1744) of Dzogchen Monastery:'
  volume:
    fEE40:
      title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence
        of the Vast Expanse
      base_file: fEE40.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
